#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.005

#define PIPE_GAP 6

#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
#define LOWER_SCREEN_PIPE_THRESHOLD 0.35

#define PIPE_MOVEMENT_SPEED 0.01

#define BIRD_COLLISION_BITMASK (1 << 0)
#define OBSTACLE_COLLISION_BITMASK (1 << 1)
#define POINT_COLLISION_BITMASK (1 << 2)

#define BIRD_FALLING_SPEED 0.0075
#define BIRD_FLYING_SPEED 0.01
#define BIRD_FLY_DURATION 0.15

#endif //  __DEFINITIONS_H__


